apiVersion: kuma.io/v1alpha1
kind: TrafficTrace
mesh: default
metadata:
  namespace: kuma-demo
  name: trace-all-traffic
spec:
  selectors:
    - match:
        kuma.io/service: "*"
  conf:
    backend: jaeger-collector
